### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by roman3017** [DF4IAH/RedPitaya_RadioBox#87]
tcl files refer to rb_broadcaster_axis_m2.xcix, which i cannot find anywhere

**Comment by DF4IAH** [comment]
Thank you! Indeed that lines in 
- __fpga/red_pitaya_vivado.tcl__  and
- __fpga/red_pitaya_vivado_project.tcl__
are not more needed anymore.

After I have the next master build ready I attach a new label to it.
Some more tweaks to be done, hopefully in abt. 1 week since now (2016-02-17) I have it done.

Cheers
  Uli

**Comment by roman3017** [comment]
I see, thanks.
